### ISSUE TITLE
Permission denied Error

### ISSUE THREAD

**Issue by deepakbs** [keedio/flume-ftp-source#10]
Hi,
I am trying to use the Flume FTP source which is using the Apache Flume 1.5.2 installed using Ambari. When the flume FTPSource is executed, after reading the file from the FTP source i get the below error
Error saving map File java.io.FileNotFoundException: hasmap.ser (Permission denied)

I presume the file is written under the /home/<user> directory
I have checked the permissions and it seems to be fine
Can you please help me solve this.

Thanks
Deepak

**Comment by lazaromedina** [comment]
Hi,
the file is written under the main folder apache-flume-1.5.X/
example: /usr/local/src/apache-flume-1.5.2-bin/
For the next version the path and file name will be configurable in the context of flume.

**Comment by deepakbs** [comment]
Perfect, thanks
