### ISSUE TITLE
Multi-threaded FTP Source

### ISSUE THREAD

**Issue by deepakbs** [keedio/flume-ftp-source#14]
Hi,

I am currently using the Flume FTP source to consume events from an FTP location. Since, the current FTP Flume source reads and processes one file at a time in a sequential manner it is unable to catch up with the speed at which events are arriving at the FTP location. Is there a way to speed up this by creating parallel FTP sources to consume from the same FTP location and speed this up.

Thanks
Deepak

**Comment by lazaromedina** [comment]
Not actually because the api FTPClient of apache is blocking.
