### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Highbrainer** [keedio/flume-ftp-source#17]
Hello, 

it seems there is a repeated typo in the README file : 
`agent.sources.ftp1.client.sources = ftp`
...
`agent.sources.ftps1.client.sources = ftps`
...
`agent.sources.sftp1.client.sources = sftp`

=> there is an extra unwanted 's' ...client.source**s**.

The good news is that the [example conf files](https://github.com/keedio/flume-ftp-source/tree/flume_ftp_dev/src/main/resources/example-configs) are correct :)

**Comment by lazaromedina** [comment]
Thanks.
