### ISSUE TITLE
nullpointer to retrieved stream when this points to soft link

### ISSUE THREAD

**Issue by lazaromedina** [keedio/flume-ftp-source#2]
on retrieving stream from soft link , inputstream points nowhere

**Comment by schmiegelow** [comment]
Can you provide a stacktrace?

**Comment by lazaromedina** [comment]
api ftpclient doesnot return the size of the linked file, but the size of the link in the remote file system. When to trying to retrieve the linked file, the inputstream contains the link. While the main logic on deferring new files from modified files int the collection discovered, process a link will not be possible.
