### ISSUE TITLE
Ability to specify directory from which data should be pulled

### ISSUE THREAD

**Issue by NitinKumar94** [keedio/flume-ftp-source#20]
From the available configurations for the ftp source, I was not able to find a property via which I configure the path to the directory from which I want to pull files.

This would mean that I would need to host files I want to handle differently in separate users home directory.

I might be misreading the documentation but I guess this is an essential feature that is required.

Thanks.

**Comment by lazaromedina** [comment]
The ftp path from where retrieve files to be processed by Flume is ftp user's home directory.
We actually think that retrieve just some files or a single subdirectory from ftp user's home directory is not an essential feature. Maybe in the future...
You are welcome to modify source code to your needs.
Regards.

**Comment by OElesin** [comment]
+1 for this

**Comment by lucarosellini** [comment]
Reopening issue: altough this feature is not essential for us, we'll definitely implement it. Cannot promise when btw.

**Comment by NitinKumar94** [comment]
I had submitted a PR for this a long time back. PR #21 .. could you look into it. Thanks!

**Comment by lazaromedina** [comment]
PR#21 - close issue
thanks
