### ISSUE TITLE
is there any way to put file's name into event headers?

### ISSUE THREAD

**Issue by wangchuande** [keedio/flume-ftp-source#27]
I want to know the files name in event process, is there any way to put the file's name into event headers?

**Comment by lazaromedina** [comment]
Such a feature is not implemented. You can:
1) use Apache Flume Interceptor
2) pull request and modify source code to you needs, for example: headers.put("filename") in processMessage.
regards

**Comment by wangchuande** [comment]
but how can i get the filename in processMessage methods?
